

export const BookData = [

    {
        id: 0,
        book_name: "Monster",
        book_description: "Naoki Urasawa’s unforgettable thriller follows a brilliant doctor’s journey into the darkest depths of the human soul.Johan is a cold and calculating killer with a mysterious past, and brilliant Dr. Kenzo Tenma is the only one who can stop him! Conspiracy and serial murder open the door to a compelling, intricately woven plot in this masterwork of suspense.Everyone faces uncertainty at some point in their lives. Even a brilliant surgeon like Kenzo Tenma is no exception. ",
        book_img:' //upload.wikimedia.org/wikipedia/en/thumb/0/00/Monster_manga_volume_1_cover.jpg/220px-Monster_manga_volume_1_cover.jpg',
        print_length: "345 pages",
        language: "English",
        author_name: "Naoki Urasawa’s",
        price: "305",
    },
    {
        id: 1,
        book_name: "CHAINSAW MAN",
        book_description: "Chainsaw Man (Japanese: チェンソーマン, Hepburn: Chensō Man) is a Japanese manga series written and illustrated by Tatsuki Fujimoto. Its first arc was serialized in Shueisha's shōnen manga magazine Weekly Shōnen Jump from December 2018 to December 2020; its second arc began serialization in Shueisha's Shōnen Jump+ online magazine in July 2022. Its chapters have been collected in 16 tankōbon volumes as of December 2023.!",
        book_img: "//upload.wikimedia.org/wikipedia/en/thumb/2/24/Chainsawman.jpg/220px-Chainsawman.jpg",
        print_length: "320 pages",
        language: "English",
        author_name: "	Tatsuki Fujimoto",
        price: "312",
    },
    {
        id: 2,
        book_name: "JUJUTSU KAISEN ",
        book_description: "For some strange reason, Yuji Itadori, despite his insane athleticism would rather just hang out with the Occult Club. However, her soon finds out that the occult is as real as it gets when his fellow club members are attacked! Meanwhile, the mysterious Megumi Fushiguro is tracking down a special-grade cursed object, and his search leads him to Itadori...",
        book_img: "//upload.wikimedia.org/wikipedia/en/thumb/4/46/Jujutsu_kaisen.jpg/220px-Jujutsu_kaisen.jpg",
        print_length: "248 pages",
        language: "English",
        author_name: "Gege Akutami",
        price: "140",
    },
    {
        id: 3,
        book_name: "Attack on Titan",
        book_description: "In this post-apocalytpic sci-fi story, humanity has been devastated by the bizarre, giant humanoids known as the Titans. Little is known about where they came from or why they are bent on consuming mankind. Seemingly unintelligent, they have roamed the world for years, killing everyone they see. For the past century, what's left of man has hidden in a giant, three-walled city. People believe their 100-meter-high walls will protect them from the Titans, but the sudden appearance of an immense Titan is about to change everything. Winner of the 2011 Kodansha Manga Award (Shonen) and nominated for the prestigious Osamu Tezuka Cultural Prize for 2012..",
        book_img: "//upload.wikimedia.org/wikipedia/en/thumb/d/d6/Shingeki_no_Kyojin_manga_volume_1.jpg/220px-Shingeki_no_Kyojin_manga_volume_1.jpg",
        print_length: "240 pages",
        language: "English",
        author_name: "Hajime Isayama",
        price: "202",
    },
    {
        id: 4,
        book_name: "Tokyo Revengers",
        book_description: "Takemichi Hanagaki's life is at an all-time low. Just when he thought it couldn't get worse, he finds out that Hinata Tachibana, his ex-girlfriend, was murdered by the Tokyo Manji Gang: a group of vicious criminals that has been disturbing society's peace for quite some time. Wondering where it all went wrong, Takemichi suddenly finds himself travelling through time, ending up 12 years in the past—when he was still in a relationship with Hinata. Realizing he has a chance to save her, Takemichi resolves to infiltrate the Tokyo Manji Gang and climb the ranks in order to rewrite the future and save Hinata from her tragic fate.",
        book_img: "//upload.wikimedia.org/wikipedia/en/thumb/b/b1/Tokyo_Revengers_volume_1_cover.jpg/220px-Tokyo_Revengers_volume_1_cover.jpg",
        print_length: "236 pages",
        language: "English",
        author_name: "Ken Wakui",
        price: "108",
    },
    {
        id: 5,
        book_name: "Naruto",
        book_description: "Naruto is a Japanese manga series written and illustrated by Masashi Kishimoto. It tells the story of Naruto Uzumaki, a young ninja who seeks recognition from his peers and dreams of becoming the Hokage, the leader of his village. The story is told in two parts: the first is set in Naruto's pre-teen years (volumes 1–27), and the second in his teens (volumes 28–72). The series is based on two one-shot manga by Kishimoto: Karakuri (1995), which earned Kishimoto an honorable mention in Shueisha's monthly Hop Step Award the following year, and Naruto (1997).",
        book_img: "//upload.wikimedia.org/wikipedia/en/thumb/9/94/NarutoCoverTankobon1.jpg/220px-NarutoCoverTankobon1.jpg",
        print_length: "172 pages",
        language: "English",
        author_name: "Masashi Kishimoto",
        price: "286",
    },
    {
        id: 6,
        book_name: "Tokyo Ghoul",
        book_description: "Tokyo Ghoul (Japanese: 東京喰種トーキョーグール, Hepburn: Tōkyō Gūru) is a Japanese dark fantasy manga series written and illustrated by Sui Ishida. It was serialized in Shueisha's seinen manga magazine Weekly Young Jump from September 2011 to September 2014, with its chapters collected in 14 tankōbon volumes. The story is set in an alternate version of Tokyo where humans coexist with ghouls, beings who look like humans but can only survive by eating human flesh. Ken Kaneki is a college student who is transformed into a half-ghoul after an encounter with one of them. He must navigate the complex social and political dynamics between humans and ghouls while struggling to maintain his humanity..",
        book_img: "//upload.wikimedia.org/wikipedia/en/thumb/e/e5/Tokyo_Ghoul_volume_1_cover.jpg/220px-Tokyo_Ghoul_volume_1_cover.jpg",
        print_length: "320 pages",
        language: "English",
        author_name: "Sui Ishida",
        price: "138",
    },
    {
        id: 7,
        book_name: "Vinland Saga ",
        book_description: "At the turn of the 11th century, the North Sea is in the grip of the Viking terror. Askeladd leads his small band of mercenaries into London, with the aid of the ruthless young Thorfinn. But Thorfinn has sworn to kill Askeladd one day to avenge hi.",
        book_img: "//upload.wikimedia.org/wikipedia/en/thumb/5/51/Vinland_Saga_volume_01_cover.jpg/220px-Vinland_Saga_volume_01_cover.jpg",
        print_length: "200 pages",
        language: "English",
        author_name: " Makoto Yukimura",
        price: "340",
    },
    {
        id: 8,
        book_name: "One Piece",
        book_description: "One Piece is a Japanese manga series written and illustrated by Eiichiro Oda. It has been serialized in Shueisha's shōnen manga magazine Weekly Shōnen Jump since July 1997, with its individual chapters compiled in 107 tankōbon volumes as of November 2023. The story follows the adventures of Monkey D. Luffy and his crew, the Straw Hat Pirates, where he explores the Grand Line in search of the mythical treasure known as the One Piece in order to become the next King of the Pirates",
        book_img: "//upload.wikimedia.org/wikipedia/en/thumb/9/90/One_Piece%2C_Volume_61_Cover_%28Japanese%29.jpg/220px-One_Piece%2C_Volume_61_Cover_%28Japanese%29.jpg",
        print_length: "224 pages",
        language: "English",
        author_name: "Eiichiro Oda",
        price: "310",
    },
    {
        id: 9,
        book_name: "Hunter x Hunter",
        book_description: "Hunter × Hunter (stylized as HUNTER×HUNTER and pronounced hunter hunter is a Japanese manga series written and illustrated by Yoshihiro Togashi. It has been serialized in Shueisha's shōnen manga magazine Weekly Shōnen Jump since March 1998, although the manga has frequently gone on extended hiatuses since 2006. Its chapters have been collected in 37 tankōbon volumes as of November 2022. The story focuses on a young boy named Gon Freecss who discovers that his father, who left him at a young age, is actually a world-renowned Hunter, a licensed professional who specializes in fantastical pursuits such as locating rare or unidentified animal species, treasure hunting, surveying unexplored enclaves, or hunting down lawless individuals. Gon departs on a journey to become a Hunter and eventually find his father. Along the way, Gon meets various other Hunters and encounters the paranormal.",
        book_img: "https://image.animationdigitalnetwork.fr/license/hunter/tv2/web/affiche_500x0.jpg",
        print_length: "384 pages",
        language: "English",
        author_name: "Yoshihiro Togashi",
        price: "272",
    },
    {
        id: 10,
        book_name: "Dragon Ball Z",
        book_description: "Dragon Ball Z[c] is a Japanese anime television series produced by Toei Animation. Part of the Dragon Ball media franchise, it is the sequel to the 1986 Dragon Ball television series and adapts the latter 325 chapters of the original Dragon Ball manga series created by Akira Toriyama. The series aired in Japan on Fuji TV from April 1989 to January 1996 and was later dubbed for broadcast in at least 81 countries worldwide.",
        book_img: "//upload.wikimedia.org/wikipedia/en/thumb/4/4c/GokumangaToriyama.png/220px-GokumangaToriyama.png",
        print_length: "208 pages",
        language: "English",
        author_name: "Takao Koyama",
        price: "249",
    },
    {
        id: 11,
        book_name: "Solo Leveling",
        book_description: "Solo Leveling, also alternatively translated as Only I Level Up (Korean: 나 혼자만 레벨업; RR: Na Honjaman Rebeleop), is a South Korean web novel written by Chugong. It was serialized in Kakao's digital comic and fiction platform KakaoPage beginning on July 25, 2016, and was later published in by D&C Media under their Papyrus label since November 4, 2016. The novel has been licensed in English by Yen Press.",
        book_img: "//upload.wikimedia.org/wikipedia/en/thumb/6/6c/Solo_Leveling_Volume_1_Cover.jpg/220px-Solo_Leveling_Volume_1_Cover.jpg",
        print_length: "256 pages",
        language: "English",
        author_name: "Chugong",
        price: "294",
    },
    {
        id: 12,
        book_name: "Death Note",
        book_description: "Death Note (stylized in all caps) is a Japanese manga series written by Tsugumi Ohba and illustrated by Takeshi Obata. It was serialized in Shueisha's shōnen manga magazine Weekly Shōnen Jump from December 2003 to May 2006, with its chapters collected in 12 tankōbon volumes. The story follows Light Yagami, a genius high school student who discovers a mysterious notebook: the Death Note, which belonged to the shinigami Ryuk, and grants the user the supernatural ability to kill anyone whose name is written in its pages. The series centers around Light's subsequent attempts to use the Death Note to carry out a worldwide massacre of individuals whom he deems immoral and to create a crime-free society, using the alias of a god-like vigilante named Kira, and the subsequent efforts of an elite Japanese police task force, led by enigmatic detective L, to apprehend him.",
        book_img: "https://dukaan.b-cdn.net/701x701/webp/upload_file_service/afd6007d-622f-47cf-8e37-9170ecdbef4e/death-note-vol-3-jpg",
        print_length: "480 pages",
        language: "English",
        author_name: "Tsugumi Ohba",
        price: "305",
    },
    {
        id: 13,
        book_name: "Parasyte",
        book_description: "Parasyte (Japanese: 寄生獣, Hepburn: Kiseijū, lit. Parasitic Beasts is a Japanese science fiction horror manga series written and illustrated by Hitoshi Iwaaki. It was published in Kodansha's Morning Open Zōkan (1989) and Monthly Afternoon (1989 to 1994). The manga was published in North America first by Tokyopop, then Del Rey, and finally Kodansha USA. The series follows Shinichi Izumi, a high school senior who is the victim of a failed attempt by a parasitic organism to take over his brain. The parasite instead infects and takes over his arm.",
        book_img: "//upload.wikimedia.org/wikipedia/en/thumb/8/87/Parasyte_4.png/220px-Parasyte_4.png",
        print_length: "640 pages",
        language: "English",
        author_name: "Hitoshi Iwaaki",
        price: "439",
    },
    {
        id: 14,
        book_name: "Black Clover",
        book_description: "Black Clover (Japanese: ブラッククローバー, Hepburn: Burakku Kurōbā) is a Japanese manga series written and illustrated by Yūki Tabata. It started in Shueisha's shōnen manga magazine Weekly Shōnen Jump in February 2015. The series ran in the magazine until August 2023, and moved to Jump Giga in December of the same year. Its chapters have been collected in 36 tankōbon volumes as of February 2024. Set in a world where everyone is given the ability to use magic, the story follows Asta, a young boy born without any magic power who is given a rare grimoire that grants him anti-magic abilities. With his fellow mages from the Black Bulls, Asta plans to become the next Wizard King.",
        book_img: "//upload.wikimedia.org/wikipedia/en/thumb/6/69/Black_Clover%2C_volume_1.jpg/220px-Black_Clover%2C_volume_1.jpg",
        print_length: "816 pages",
        language: "English",
        author_name: "Yūki Tabata",
        price: "475",
    }
]